### PR TITLE
Remove "Opal Quirk"

### PR DESCRIPTION
**Pull request by Opalinium**
This is quite literally harassment

### CODE REVIEW

**Comment by poke5352** [comment]
nah its perfect keep it

**Comment by CactusDuper** [comment]
😳 what if 🤔 instead 😈 of doing zany 🤪 it did 🤩 cactus 🌵 for cactus 😏 it might 🤭 be better 🤫 don't tell 😬 the bot 🤖 but i like 😤 cheeseburger 🥴

**Comment by flamingowrangler2869** [comment]
🤪pal quirk

**Comment by hewwo-owo1** [comment]
Nah, this ain't harassment If there's anything wrong here, its abusing the :zany_face: emoji. I think going with Cactus's idea will do some good, switching it out to :cactus: is really gonna be perfect uwu.

**Review by poke5352 — CHANGES_REQUESTED** [review]
Change zany face to cactus

**Comment by CactusDuper** [comment]
✋ what if we made it cactus 🌵 only for me 😳 it would be pretty poggers 🥴 not as poggers as emojis though 😏. Wyd if resbot 🤖 comes is your house 🏡 at night 🌚 and whispers in your ear 👂 that it's zany face time 🤪

**Pull request closed without merging**
